version: "3.8"
services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - ecommerce-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    networks:
      - ecommerce-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
